# Generated by Django 4.2.3 on 2024-03-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/assignments/')),
                ('assignment_details', models.TextField()),
                ('last_date_of_submission', models.DateField()),
                ('teacher_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chat_photos/')),
                ('class_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('chat_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Chat_messages',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('exam_name', models.CharField(max_length=255)),
                ('paper_file_path', models.FileField(upload_to='exam_papers/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='homework_photos/')),
                ('class_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ReminderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('sent_by', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reminder_message',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=255)),
                ('result_photo', models.ImageField(upload_to='photos/results/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('date_of_payment', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
                ('time_of_payment', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/timetables/')),
                ('occasion', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Timetable',
            },
        ),
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('users', models.JSONField()),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('date_of_payment', models.DateField()),
                ('last_date_of_payment', models.DateField()),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('month', models.CharField(max_length=20)),
                ('fees_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_categories', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.usersdata')),
            ],
            options={
                'db_table': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('month_year', models.CharField(max_length=7)),
                ('class_name', models.CharField(max_length=255)),
                ('attendance_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.usersdata')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
